sonar.projectKey=gpu-workload-supervisor
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/node_modules/**,**/coverage.out,**/.github/**,**/docs/**
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
